# Generated by Django 6.0 on 2026-08-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('host_player', models.CharField(max_length=100)),
                ('host_player_id', models.CharField(max_length=50)),
                ('join_player', models.CharField(blank=True, max_length=100, null=True)),
                ('join_player_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('analyzing', 'Analyzing'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('game_mode', models.CharField(default='coding', max_length=20)),
                ('difficulty', models.CharField(default='easy', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('winner_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
