# Generated by Django 6.0 on 2026-08-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroom',
            name='quiz_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
