# Generated by Django 6.0 on 2026-08-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_battleroom_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroom',
            name='host_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleroom',
            name='host_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battleroom',
            name='host_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleroom',
            name='join_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleroom',
            name='join_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battleroom',
            name='join_time',
            field=models.IntegerField(default=0),
        ),
    ]
