# Generated by Django 6.0 on 2026-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career_dna_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roadmap_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_gaps_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
