# Generated by Django 6.0 on 2026-08-12 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_career_dna_data_userprofile_roadmap_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('difficulty', models.CharField(default='Medium', max_length=50)),
                ('interview_type', models.CharField(default='Technical', max_length=50)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='ongoing', max_length=20)),
                ('technical_score', models.IntegerField(blank=True, null=True)),
                ('communication_score', models.IntegerField(blank=True, null=True)),
                ('problem_solving_score', models.IntegerField(blank=True, null=True)),
                ('clarity_score', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.IntegerField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('areas_to_improve', models.JSONField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('is_coding', models.BooleanField(default=False)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.interviewsession')),
            ],
        ),
    ]
